# 指定語言環境
language: node_js
# 是否需要 sudo 權限
sudo: false
# 指定版本
node_js:
  - "12"
# 指定暫存空間，如果有指定會編譯比較快。
cache:
  directories:
    - node_modules
# 指定 Hexo 專案的分支，這一個看狀況來設置，如果你的專案有特別做分支管理的，那就要改一下
# 簡單來講就是監聽這個分支的變化
branches:
  only:
    - master
# 安裝 cli 套件
before_script:
  - npm install -g hexo-cli
# 還原套件
install:
  - npm install
# 執行指令
script:
  - hexo clean # 先清除緩存
  - hexo generate # 生成靜態網頁
# 部屬設置
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUBHEXO_TOKEN
  keep-history: true
  target-branch: master #部署到master分支
  on:
    branch: master
  local-dir: public